### ISSUE TITLE
Change return type of `new*` functions on `ResourcePool` to a `Result`

### ISSUE THREAD

**Issue by bzm3r** [Leafwing-Studios/leafwing_abilities#16]
## Which code could be improved?

https://github.com/Leafwing-Studios/leafwing_abilities/blob/45cb55c4dd0674849efec65dbc17953633cf1ff3/src/pool.rs#L51

https://github.com/Leafwing-Studios/leafwing_abilities/blob/45cb55c4dd0674849efec65dbc17953633cf1ff3/src/pool.rs#L58

https://github.com/Leafwing-Studios/leafwing_abilities/blob/45cb55c4dd0674849efec65dbc17953633cf1ff3/src/pool.rs#L67

## How should this be changed?

Note that the docs for `new` say:

https://github.com/Leafwing-Studios/leafwing_abilities/blob/45cb55c4dd0674849efec65dbc17953633cf1ff3/src/pool.rs#L46-L50

These should return `Result<Self, MaxPoolLessThanZero>`, that way, the expectation described in the doc is guaranteed to be fulfilled.

**Comment by alice-i-cecile** [comment]
Went with #18 instead.
