### ISSUE TITLE
CooldownState::trigger can incorrectly(?) put something on cooldown

### ISSUE THREAD

**Issue by alanbaumgartner** [Leafwing-Studios/leafwing_abilities#71]
## Which feature is frustrating to use or confusing?

```
This can be paired with [`Cooldowns::ready`],
to check if the action can be used before triggering its cooldown,
or this can be used on its own,
reading the returned [`Result`] to determine if the ability was used.
```

Based on the docs, I expect that if this function returns an error indicating an ability was not used, it should not also trigger the non-global cooldown.
I also take the docs to mean, I can skip calling `ready` and use the result here.

Because this can be called without first calling `CooldownState::ready`, it may trigger the ability cooldown but then fail on the global cooldown.

## Expectation

`CooldownState::trigger` does not trigger cooldowns if an ability was not used.

## Proposal

I believe `CooldownState::trigger` should call `CooldownState::ready` itself, prior to attempting to trigger the ability and global cooldowns.
```rust
    pub fn trigger(&mut self, action: &A) -> Result<(), CannotUseAbility> {
        self.ready(action)?;

        if let Some(cooldown) = self.get_mut(action) {
            cooldown.trigger()?;
        }

        if let Some(global_cooldown) = self.global_cooldown.as_mut() {
            global_cooldown.trigger()?;
        }

        Ok(())
    }
```

I am willing to PR this if the above is agreeable 😄, I am also willing to take a stab at #36 and #51 if they are still applicable.

**Comment by alice-i-cecile** [comment]
That sounds great. #51 is definitely applicable, and I think we can borrow from LWIM for #36.
